version: 0.2 

phases:
  install:
    commands:
      - echo Installing NGINX Server
      - sudo apt-get update
      - sudo apt-get install nginx -y
  
  build:
    commands:
      - echo Build Phase started on 'date'
      - cp index.html /var/www/html/

  post_build:
    commands:
      - echo Configuring NGINX Server
    
artifacts:
  files:
    - '**/*'